#============START================
install.packages("remotes")
install.packages("Rcmdr", dependencies = TRUE)
install.packages("ggplot2")
install.packages("medicaldata")
install.packages("modeest")
install.packages("moments")
install.packages("Hmisc")
install.packages("tigerstats")
install.packages("BSDA")
install.packages("tidyverse")
install.packages("rstatix")
install.packages("lmtest")
install.packages("NHSRdatasets")
install.packages("dgof")
install.packages("caTools")
install.packages("pscl")
install.packages("caret")
install.packages ("readxl")
install.packages("writexl")
install.packages("datarium")
install.packages("gmodels")
install.packages("epiDisplay")
install.packages("prettyR")
install.packages("psych")
install.packages("lessR")
install.packages("catspec")
install.packages("vcd")
install.packages("tables")
install.packages("pastecs")
install.packages("fields")
install.packages("Zelig")
install.packages("QuantPsyc")
install.packages("olsrr")
install.packages("DescTools")
install.packages("AER")
install.packages("msme")
install.packages("COUNT")
install.packages("gamlss")
install.packages("survminer")
install.packages("ggpubr")
install.packages("ggsignif")
install.packages("rms")
install.packages("ggfortify")
install.packages("timereg")
install.packages("gtsummary")
install.packages("lsr")
install.packages("jtools")
install.packages("remotes")
remotes::install_github("carlganz/svrepmisc")
install.packages("misty")
install.packages("gamlss.mx")
install.packages("MCMCglmm")
install.packages("ggResidpanel")
install.packages("r2mlm")
install.packages("countreg", repos="http://R-Forge.R-project.org")
install.packages("performance")
install.packages("generalhoslem")
install.packages("ResourceSelection")
install.packages("meta")
install.packages("metafor")
install.packages("metasens")
install.packages("topmodels", repos = "https://r-forge.r-project.org/")
install.packages("distributions3")

# ---
#========================END======================================